openapi: 3.0.1
info:
  title: Sports Store Service
  version: 1.0.0
servers:
  - url: localhost:8080/
paths:
  /store-info:
    get:
      summary: GetStoreInfo
      description: Get the store info details
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getStoreInfoResp'
                
  /sports/{id}:
    get:
      summary: GetSportByID
      description: Get sport by ID
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getSportResp'                
  /sports:
    get:
      summary: GetSports
      description: Get sports
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getSportsResp'
               
components:
  schemas:
    getStoreInfoResp:
      type: object
      description: Get Store info Response object
      properties:
        item_name:
          type: string
        upload_timestamp:
          type: string
        sell_timestamp:
          type: string
        price:
          type: number
          
    getSportsResp:
      type: object
      description: Get Sports response object
      properties:
        user_data:
          type: array
          description: Individual sport data object
          items:
            properties:
              name:
                type: string
              sport_id:
                type: string
              type:
                type: string
              player_count:
                type: number
                
    getSportResp:
      type: object
      description: Individual sport data object
      properties:
        name:
          type: string
        sport_id:
          type: string
        type:
          type: string
        player_count:
          type: number
